### PR TITLE
Added 0 feature

### PR DESCRIPTION
**Pull request by Causality-C**
Problem: Zero button wasn't working
Solution: Now it works boom

### CODE REVIEW

**Comment by zhuolix** [comment]
~~lgqm~~ lgtm

**Comment by VincentDo8439** [comment]
LGTM! 👍

**Comment by aarushic** [comment]
hi

**Comment by Emerald-Z** [comment]
hello

**Comment by connyycai** [comment]
boom!

**Comment by aarushic** [comment]
😀

**Comment by Causality-C** [comment]
:lipstick: Nice

**Comment by nayeonkim511** [comment]
👍

**Comment by sarayuc** [comment]
hellooooo

**Pull request merged**
